# Generated by Django 4.2.3 on 2023-07-14 02:16

import cursos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('inscricao_curricular', models.CharField(max_length=255)),
                ('data_criacao', models.DateField()),
                ('descricao', models.TextField()),
                ('informacoes_complementares', models.TextField(blank=True)),
                ('capa', models.FileField(blank=True, upload_to='capas/', validators=[cursos.models.validate_pdf_file])),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mural', models.CharField(choices=[('G', 'Gerenciador'), ('E', 'Equipe')], max_length=1)),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.FileField(upload_to='relatorios/', validators=[cursos.models.validate_pdf_file])),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
        ),
    ]
