# Generated by Django 4.2.3 on 2023-07-14 16:45

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('inscricao_curricular', models.CharField(max_length=255)),
                ('data_criacao', models.DateField()),
                ('descricao', models.TextField()),
                ('informacoes_complementares', models.TextField(blank=True)),
                ('mural_gen', models.TextField(blank=True)),
                ('mural_eq', models.TextField(blank=True)),
                ('capa', models.FileField(blank=True, upload_to='capas/', validators=[validators.validate_pdf_file])),
            ],
        ),
    ]
