# Generated by Django 4.2.3 on 2023-07-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='mural_eq',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='mural_gen',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Mural',
        ),
    ]
